name: Build & Release NextYT

on:
  push:
    tags:
      - "v*"

jobs:
  build:
    name: Build for ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    timeout-minutes: 60
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: Setup FFmpeg (macOS)
        if: runner.os == 'macOS'
        run: brew install ffmpeg

      - name: Setup FFmpeg (Linux)
        if: runner.os == 'Linux'
        uses: FedericoCarboni/setup-ffmpeg@v3

      - name: Setup FFmpeg (Windows)
        if: runner.os == 'Windows'
        uses: FedericoCarboni/setup-ffmpeg@v3

      - name: Setup yt-dlp
        uses: AnimMouse/setup-yt-dlp@v3
        with:
          ffmpeg: false

      - name: Verify ffmpeg, ffprobe, yt-dlp (Unix)
        if: runner.os != 'Windows'
        run: |
          which ffmpeg
          which ffprobe
          which yt-dlp
          ffmpeg -version
          ffprobe -version
          yt-dlp --version

      - name: Verify ffmpeg, ffprobe, yt-dlp (Windows)
        if: runner.os == 'Windows'
        shell: pwsh
        run: |
          Get-Command ffmpeg
          Get-Command ffprobe
          Get-Command yt-dlp
          ffmpeg -version
          ffprobe -version
          yt-dlp --version

      - name: Install dependencies (Bun)
        run: bun install --no-progress
        shell: bash

      - name: Stage binaries (Linux/macOS)
        if: runner.os != 'Windows'
        run: |
          mkdir -p apps/desktop/src/binaries
          cp "$(command -v ffmpeg)"  apps/desktop/src/binaries/ffmpeg
          cp "$(command -v ffprobe)" apps/desktop/src/binaries/ffprobe
          cp "$(command -v yt-dlp)"  apps/desktop/src/binaries/yt-dlp
          chmod +x apps/desktop/src/binaries/*

      - name: Stage binaries (Windows)
        if: runner.os == 'Windows'
        shell: pwsh
        run: |
          New-Item -ItemType Directory -Force -Path apps/desktop/src/binaries | Out-Null
          Copy-Item (Get-Command ffmpeg).Source  apps/desktop/src/binaries/ffmpeg.exe  -Force
          Copy-Item (Get-Command ffprobe).Source apps/desktop/src/binaries/ffprobe.exe -Force
          Copy-Item (Get-Command yt-dlp).Source  apps/desktop/src/binaries/yt-dlp.exe  -Force

      - name: List staged binaries (Unix)
        if: runner.os != 'Windows'
        run: ls -lah apps/desktop/src/binaries

      - name: List staged binaries (Windows)
        if: runner.os == 'Windows'
        shell: pwsh
        run: Get-ChildItem -Path apps/desktop/src/binaries -Force

      - name: Build and Publish
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: bun run publish
